#!/usr/bin/python
import teatime.database
import teatime.models  # Bootstrap db models

from teatime.config import TeaTimeConfig


def main():
    conf = TeaTimeConfig.from_default_file()
    database = teatime.database.DatabaseConnection.from_teatime_config(conf)
    database.connect(teatime.database.Base, echo=True)

if __name__ == '__main__':
    main()
